---
galaxy_info:
  role_name: nginx
  author: devops
  description: Installs and configures NGINX on Debian/Ubuntu
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
        - noble
    - name: Debian
      versions:
        - bullseye
        - bookworm

dependencies: []
